spring:
  application:
    name: cloud-config-center-3
  cloud:
    config:
      server:
        git:
          uri: git@github.com:yanjingyu007/SpringcloudConfig.git #github上仓库的名字
          username: yanjingyu007 
          password: zzzxxxsss000
          search-paths:
            - SpringcloudConfig
      label: master
